namespace SupportTicketing.Domain.Enums;

/// <summary>
/// Workflow states. Persisted as <see cref="int"/>; the allowed edges between them
/// live in the TicketStatusTransitions table so the workflow stays configurable
/// without a code change or a migration.
/// </summary>
public enum TicketStatus
{
    New = 1,
    Assigned = 2,
    InProgress = 3,
    WaitingForRequester = 4,
    WaitingForThirdParty = 5,
    Escalated = 6,
    Resolved = 7,
    Closed = 8,
    Reopened = 9,
    Cancelled = 10
}

public enum TicketType
{
    Incident = 1,
    ServiceRequest = 2,
    SoftwareBug = 3,
    DataCorrection = 4,
    AccessRequest = 5,
    FeatureRequest = 6,
    TrainingRequest = 7,
    SecurityIncident = 8,
    IntegrationFailure = 9
}

/// <summary>How widely the issue is felt. One axis of the priority matrix.</summary>
public enum ImpactLevel
{
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4
}

/// <summary>How quickly the issue must be addressed. The other axis of the priority matrix.</summary>
public enum UrgencyLevel
{
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4
}

/// <summary>
/// Calculated from impact and urgency via the configurable matrix. Never taken
/// directly from requester input.
/// </summary>
public enum PriorityLevel
{
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4
}

/// <summary>Technical severity, recorded independently of business priority.</summary>
public enum SeverityLevel
{
    Minor = 1,
    Moderate = 2,
    Major = 3,
    Critical = 4
}

public enum TicketSource
{
    Portal = 1,
    Agent = 2,
    Email = 3,
    Api = 4,
    Integration = 5,
    Phone = 6,
    Chat = 7
}

/// <summary>
/// Records whether a decision was made by a person, a deterministic rule, an AI
/// recommendation, or a background job. Required to answer "was this decided by a
/// person, a rule, or AI?" for any field on any ticket.
/// </summary>
public enum DecisionSource
{
    Human = 1,
    Rule = 2,
    Ai = 3,
    System = 4
}

public enum CommentType
{
    /// <summary>Visible to the requester.</summary>
    PublicReply = 1,

    /// <summary>Support staff only. Excluded server-side from every requester-facing surface.</summary>
    InternalNote = 2,

    /// <summary>Generated by the system, for example a status change or an SLA event.</summary>
    SystemEvent = 3
}

public enum AssignmentMethod
{
    Manual = 1,
    RoundRobin = 2,
    LeastActive = 3,
    WeightedWorkload = 4,
    SkillBased = 5,
    RoutingRule = 6,
    AiRecommended = 7,
    SelfAssigned = 8
}

public enum SlaTimerState
{
    NotStarted = 0,
    Running = 1,
    Paused = 2,
    Met = 3,
    Breached = 4,
    Cancelled = 5
}

public enum SlaEventType
{
    Started = 1,
    Paused = 2,
    Resumed = 3,
    FirstResponseRecorded = 4,
    WarningRaised = 5,
    ResponseBreached = 6,
    ResolutionBreached = 7,
    Escalated = 8,
    Completed = 9,
    Cancelled = 10,
    Overridden = 11
}

public enum EscalationTrigger
{
    SlaWarning = 1,
    SlaBreach = 2,
    NotAccepted = 3,
    Manual = 4,
    CriticalPriority = 5,
    RequesterRejected = 6
}

public enum EscalationState
{
    Raised = 1,
    Notified = 2,
    Acknowledged = 3,
    Resolved = 4,
    Cancelled = 5
}

public enum NotificationChannel
{
    InApp = 1,
    Email = 2,
    Sms = 3,
    Webhook = 4
}

public enum NotificationDeliveryState
{
    Pending = 1,
    Sent = 2,
    Failed = 3,
    DeadLettered = 4,
    Suppressed = 5
}

public enum NotificationEventType
{
    TicketCreated = 1,
    TicketAssigned = 2,
    TicketReplied = 3,
    TicketStatusChanged = 4,
    SlaWarning = 5,
    SlaBreached = 6,
    TicketEscalated = 7,
    TicketResolved = 8,
    TicketClosed = 9,
    TicketReopened = 10,
    MentionedInComment = 11
}

public enum AttachmentScanState
{
    Pending = 1,
    Clean = 2,
    Infected = 3,
    ScanFailed = 4,
    Skipped = 5
}

public enum ArticleStatus
{
    Draft = 1,
    InReview = 2,
    Published = 3,
    Archived = 4
}

public enum ArticleVisibility
{
    /// <summary>Support staff only.</summary>
    Internal = 1,

    /// <summary>Visible to requesters inside the owning organization.</summary>
    Organization = 2,

    /// <summary>Visible to every authenticated user across organizations.</summary>
    Public = 3
}

public enum ClosureReason
{
    ResolvedConfirmed = 1,
    AutoClosedNoResponse = 2,
    Duplicate = 3,
    NoLongerRequired = 4,
    CannotReproduce = 5,
    RejectedOutOfScope = 6,
    CancelledByRequester = 7
}

/// <summary>Types of ERP or operational record a ticket can reference.</summary>
public enum RelatedRecordType
{
    PurchaseOrder = 1,
    Style = 2,
    Customer = 3,
    Supplier = 4,
    Factory = 5,
    Merchant = 6,
    ProductionOrder = 7,
    Inspection = 8,
    Shipment = 9,
    Invoice = 10,
    DebitNote = 11,
    CommissionInvoice = 12,
    DigitalProductPassport = 13,
    Integration = 14,
    Other = 99
}

public enum AuditAction
{
    Created = 1,
    Updated = 2,
    Deleted = 3,
    LoginSucceeded = 4,
    LoginFailed = 5,
    LoggedOut = 6,
    PasswordChanged = 7,
    TokenRefreshed = 8,
    TokenReuseDetected = 9,
    PermissionChanged = 10,
    RoleChanged = 11,
    StatusChanged = 12,
    Assigned = 13,
    PriorityChanged = 14,
    Escalated = 15,
    SlaOverridden = 16,
    AttachmentUploaded = 17,
    AttachmentDownloaded = 18,
    Exported = 19,
    AiRecommendationAccepted = 20,
    AiRecommendationRejected = 21,
    ConfigurationChanged = 22,
    AccessDenied = 23
}
