<#
.SYNOPSIS
  Deploys or redeploys the Support Ticketing API to IIS on this machine.

.DESCRIPTION
  Copies a published build into place and makes IIS able to run it: an
  application pool that does not idle out, a site or application pointing at
  the folder, file permissions for the pool identity, and a SQL Server login
  for that identity. Then it starts the pool, waits for /health/ready, and
  restarts once more because the escalation ladder is created on the second
  start.

  The first run creates everything. Later runs only replace the build and leave
  the server's web.config alone: that file carries the connection string, the
  signing key and the CORS list, and the one generated by `dotnet publish` has
  none of them.

  Run from an elevated PowerShell. Requires the ASP.NET Core Hosting Bundle,
  which is not the same thing as the runtime; without it every request returns
  500.19 before the application is ever started.

.PARAMETER Payload
  The folder produced by `dotnet publish -c Release -o <Payload>`.

.PARAMETER Name
  Name for the site (or application) and its pool. Also the folder name.

.PARAMETER Port
  Creates a standalone site bound to this port. Omit to attach the API as an
  application under the Default Web Site at /<Name> instead.

.PARAMETER DataRoot
  Where uploads and logs live. Deliberately outside the web root: uploads
  served straight by IIS would bypass every authorisation check in the
  download endpoint, and logs inside the site folder are destroyed by the next
  deploy.

.EXAMPLE
  dotnet publish src/SupportTicketing.Api -c Release -o publish
  .\deploy\iis\Deploy-Api.ps1 -Payload .\publish -Name SupportTicketingApi -Port 8080

.EXAMPLE
  # Second and later deployments: same command. web.config on the server is kept.
  .\deploy\iis\Deploy-Api.ps1 -Payload .\publish -Name SupportTicketingApi -Port 8080
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $Payload,
    [string] $Name      = 'SupportTicketingApi',
    [int]    $Port      = 0,
    [string] $SiteRoot  = 'C:\inetpub',
    [string] $DataRoot  = 'C:\SupportTicketingData',
    [string] $SqlServer = '.',
    [string] $Database  = 'SupportTicketing'
)

$ErrorActionPreference = 'Stop'

$AppPath  = Join-Path $SiteRoot $Name
$Identity = "IIS APPPOOL\$Name"
$LogPath  = Join-Path $DataRoot 'logs'

function Step($n, $text) { Write-Host "`n[$n] $text" -ForegroundColor Cyan }
function Ok($text)       { Write-Host "    $text" -ForegroundColor Green }
function Note($text)     { Write-Host "    $text" -ForegroundColor Yellow }

# ---------------------------------------------------------------- 0. checks
Step 0 'Prerequisites'

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw 'Not elevated. Open PowerShell with "Run as administrator" and try again.'
}

if (-not (Test-Path 'C:\Program Files\IIS\Asp.Net Core Module\V2')) {
    throw @'
ASP.NET Core Hosting Bundle is not installed. The runtime alone is not enough:
the bundle is what registers the ASP.NET Core Module with IIS, and without it
every request returns 500.19 before the application is ever started.

  https://dotnet.microsoft.com/download/dotnet/10.0
  -> ASP.NET Core Runtime -> Hosting Bundle

Install it, run "iisreset", then run this script again.
'@
}
Ok 'hosting bundle present'

$Payload = (Resolve-Path $Payload).Path
if (-not (Test-Path (Join-Path $Payload 'SupportTicketing.Api.dll'))) {
    throw "No published build at $Payload. Run: dotnet publish src/SupportTicketing.Api -c Release -o <folder>"
}
if (Test-Path (Join-Path $Payload 'appsettings.Development.json')) {
    throw 'appsettings.Development.json is in the payload. That is a build from before the project stopped publishing it; rebuild from current source.'
}
Ok 'payload present'

Import-Module WebAdministration

# ---------------------------------------------------------------- 1. copy
Step 1 "Build -> $AppPath"

$firstDeploy = -not (Test-Path (Join-Path $AppPath 'web.config'))

foreach ($folder in $AppPath, $DataRoot, (Join-Path $DataRoot 'attachments'), $LogPath) {
    if (-not (Test-Path $folder)) { New-Item -ItemType Directory -Path $folder | Out-Null }
}

if (-not $firstDeploy -and (Test-Path "IIS:\AppPools\$Name")) {
    if ((Get-WebAppPoolState $Name).Value -ne 'Stopped') { Stop-WebAppPool $Name }
    Start-Sleep -Seconds 3
}

# /MIR so files that no longer exist are removed. /XF web.config so the server's
# configured copy is never replaced by the bare one dotnet publish generates.
$exclude = @()
if (-not $firstDeploy) { $exclude = @('/XF', 'web.config') }
robocopy $Payload $AppPath /MIR /NFL /NDL /NJH /NJS /NP @exclude | Out-Null
if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
$LASTEXITCODE = 0

if ($firstDeploy) {
    $template = Join-Path $PSScriptRoot '..\..\src\SupportTicketing.Api\web.config.iis-template'
    if (Test-Path $template) {
        Copy-Item $template (Join-Path $AppPath 'web.config') -Force
        Note "First deployment: web.config is the TEMPLATE. Edit it before the site will start:"
        Note "  $AppPath\web.config"
        Note '  connection string, Jwt__SigningKey, Cors__AllowedOrigins, Bootstrap__*'
        Note "  and add: Storage__RootPath=$DataRoot\attachments"
        Note "           Serilog__WriteTo__1__Args__path=$LogPath\support-ticketing-.log"
    }
} else {
    Ok 'web.config on the server kept'
}
Ok "$((Get-ChildItem $AppPath -File).Count) files"

# ---------------------------------------------------------------- 2. pool
Step 2 "Application pool '$Name'"

if (-not (Test-Path "IIS:\AppPools\$Name")) { New-WebAppPool -Name $Name | Out-Null }

# Not a .NET Framework application: IIS only forwards to a Kestrel process.
Set-ItemProperty "IIS:\AppPools\$Name" managedRuntimeVersion ''

# The email dispatcher and the SLA escalation scanner are hosted services. On
# the default idle timeout IIS stops the worker after twenty quiet minutes and
# both simply stop: no error, no escalations, no mail.
Set-ItemProperty "IIS:\AppPools\$Name" startMode 'AlwaysRunning'
Set-ItemProperty "IIS:\AppPools\$Name" processModel.idleTimeout ([TimeSpan]::Zero)
Set-ItemProperty "IIS:\AppPools\$Name" recycling.periodicRestart.time ([TimeSpan]::Zero)
Ok 'no managed code, always running, no idle timeout'

# ---------------------------------------------------------------- 3. site
if ($Port -gt 0) {
    Step 3 "Site '$Name' on port $Port"
    if (-not (Test-Path "IIS:\Sites\$Name")) {
        New-Website -Name $Name -Port $Port -PhysicalPath $AppPath -ApplicationPool $Name | Out-Null
    } else {
        Set-ItemProperty "IIS:\Sites\$Name" physicalPath    $AppPath
        Set-ItemProperty "IIS:\Sites\$Name" applicationPool $Name
    }
    $Url = "http://localhost:$Port"
} else {
    Step 3 "Application 'Default Web Site/$Name'"
    if (-not (Test-Path 'IIS:\Sites\Default Web Site')) {
        throw 'Default Web Site does not exist. Pass -Port to create a standalone site instead.'
    }
    # An Application, not a virtual directory: a plain folder under the Default
    # Web Site runs in DefaultAppPool under .NET CLR v4, which cannot host this.
    $existing = Get-WebApplication -Site 'Default Web Site' -Name $Name -ErrorAction SilentlyContinue
    if ($null -eq $existing) {
        New-WebApplication -Site 'Default Web Site' -Name $Name -PhysicalPath $AppPath -ApplicationPool $Name | Out-Null
    } else {
        Set-ItemProperty "IIS:\Sites\Default Web Site\$Name" physicalPath    $AppPath
        Set-ItemProperty "IIS:\Sites\Default Web Site\$Name" applicationPool $Name
    }
    $Url = "http://localhost/$Name"
}
Ok "$Url -> $AppPath"

# ---------------------------------------------------------------- 4. rights
Step 4 'File permissions and SQL login'

# Read on the application, modify only on data and logs, so a compromised
# request cannot rewrite the binaries it is running from.
icacls $AppPath  /grant "${Identity}:(OI)(CI)RX" /T /Q | Out-Null
icacls $DataRoot /grant "${Identity}:(OI)(CI)M"  /T /Q | Out-Null
Ok "$Identity : read on app, modify on $DataRoot"

# The pool runs as a virtual account, so SQL needs a login for it by name.
# db_owner is deliberately not granted: migrations are run by a person, once,
# with their own credentials (see docs/DEPLOYMENT.md section 3).
$sql = "IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'$Identity') CREATE LOGIN [$Identity] FROM WINDOWS; " +
       "USE [$Database]; " +
       "IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$Identity') CREATE USER [$Identity] FOR LOGIN [$Identity]; " +
       "ALTER ROLE db_datareader ADD MEMBER [$Identity]; " +
       "ALTER ROLE db_datawriter ADD MEMBER [$Identity]; " +
       "GRANT EXECUTE TO [$Identity];"
try {
    $connection = New-Object System.Data.SqlClient.SqlConnection("Server=$SqlServer;Database=master;Trusted_Connection=True;TrustServerCertificate=True")
    $connection.Open()
    $command = $connection.CreateCommand()
    $command.CommandText = $sql
    $command.ExecuteNonQuery() | Out-Null
    $connection.Close()
    Ok "$Identity : db_datareader, db_datawriter, EXECUTE on $Database"
} catch {
    Note "SQL login not created: $($_.Exception.Message)"
    Note 'If the database is on another server, or uses SQL authentication, grant the'
    Note 'application login yourself (docs/DEPLOYMENT.md section 4) and put it in the'
    Note 'connection string in web.config.'
}

if ($firstDeploy) {
    Write-Host "`nStopping here: web.config still holds template values." -ForegroundColor Yellow
    Write-Host "Edit $AppPath\web.config, then run this script again."
    exit 0
}

# ---------------------------------------------------------------- 5. start
Step 5 'Starting'

Start-WebAppPool $Name -ErrorAction SilentlyContinue
if ($Port -gt 0) { Start-Website $Name -ErrorAction SilentlyContinue }

$ready = $false
foreach ($attempt in 1..30) {
    Start-Sleep -Seconds 2
    try {
        if ((Invoke-WebRequest "$Url/health/ready" -UseBasicParsing -TimeoutSec 5).StatusCode -eq 200) { $ready = $true; break }
    } catch { }
}

if (-not $ready) {
    Write-Host "`n    $Url/health/ready did not answer." -ForegroundColor Red
    Write-Host "    Read $LogPath first."
    Write-Host '    If that folder is empty the process never started: set'
    Write-Host '    stdoutLogEnabled="true" in web.config, retry, and read'
    Write-Host "    $AppPath\logs\stdout*.log."
    exit 1
}
Ok 'health/ready 200, database reachable'

# ---------------------------------------------------------------- 6. again
Step 6 'Restarting once more'

# The escalation ladder is created on the second start, not the first. Skip
# this and you get a system that looks healthy and never escalates anything.
Restart-WebAppPool $Name
Start-Sleep -Seconds 10

Write-Host "`nDone." -ForegroundColor Green
Write-Host "  API     $Url"
Write-Host "  health  $Url/health/ready"
Write-Host "  logs    $LogPath"
Write-Host "  uploads $DataRoot\attachments"
